name: run_tracker
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

  # IMPORT LIBRARIES
  shared_preferences: ^2.0.6
  #toast: ^0.1.5
  fluttertoast: ^8.0.7
  permission_handler: ^8.1.2
  syncfusion_flutter_gauges: ^19.2.47
  google_maps_flutter: ^2.0.6
  location: ^4.3.0
  geolocator: ^7.3.0
  flutter_polyline_points: ^1.0.0
  pedometer: ^3.0.0
  lottie: ^1.1.0
  flutter_rating_bar: ^4.0.0
  floor: ^1.1.0
  path_provider:
  solid_bottom_sheet: ^0.1.10
  date_picker_timeline: ^1.2.3
  fl_chart: ^0.36.2
  stop_watch_timer: ^1.3.1
  date_format: ^2.0.2
  flutter_local_notifications: ^5.0.0+4
  flutter_native_timezone: ^1.0.10
  charts_flutter: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^1.1.0
  build_runner: ^2.0.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-Bold.ttf
          weight: 600
        - asset: fonts/Roboto-Black.ttf
          weight: 700


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/
   - assets/icons/
   - assets/icons/water/
   - assets/icons/ic_back.png
   - assets/icons/ic_person_walk.png
   - assets/icons/ic_person_run.png
   - assets/icons/ic_footstep.webp
   - assets/icons/ic_steps.png
   - assets/icons/ic_water.png
   - assets/icons/ic_route_map.png
   - assets/icons/ic_best_pace.png
   - assets/icons/ic_distance.webp
   - assets/icons/ic_duration.webp
   - assets/icons/ic_male.png
   - assets/icons/ic_info_white.png
   - assets/icons/ic_female.png
   - assets/icons/ic_select_pointer.png
   - assets/icons/ic_setalite.png
   - assets/icons/ic_person_bottombar.webp
   - assets/icons/ic_map_permission.png
   - assets/icons/ic_setting_circular.png
   - assets/icons/ic_emoji_bad.webp
   - assets/icons/ic_emoji_good.webp
   - assets/icons/ic_emoji_great.webp
   - assets/icons/ic_setting.png
   - assets/icons/ic_emoji_okay.webp
   - assets/icons/ic_emoji_terrible.webp
   - assets/icons/ic_star.webp
   - assets/icons/ic_setting_round.png
   - assets/icons/ic_round_true.webp
   - assets/icons/ic_best_pace_light.webp
   - assets/icons/ic_distance_light.webp
   - assets/icons/ic_duration_light.webp
   - assets/icons/ic_selected_profile_bottombar.webp
   - assets/icons/ic_unselected_profile_bottombar.webp
   - assets/icons/ic_selected_home_bottombar.webp
   - assets/icons/ic_unselected_home_bottombar.webp
   - assets/icons/ic_options.png
   - assets/icons/ic_arrow_green_gradient.png
   - assets/icons/ic_options_steps_indicator.png
   - assets/icons/ic_edit.png
   - assets/icons/ic_reset.png
   - assets/icons/ic_turn_off.png
   - assets/icons/ic_statistics.png
   - assets/icons/ic_star_blue.png
   - assets/icons/ic_trouble_shooting.png
   - assets/icons/ic_yellow_gradient_circle.png
   - assets/icons/ic_red_gradient_circle.png
   - assets/icons/ic_add.png
   - assets/icons/ic_minus.png
   - assets/images/
   - assets/images/dummy_girl.png
   - assets/images/finish_image.png
   - assets/images/bg_countdown_timer_blue.webp
   - assets/images/bg_countdown_timer_green.webp
   - assets/animation/
   - assets/animation/countdown_blue.json
   - assets/animation/countdown_green.json


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
